### ISSUE TITLE
Can you add more example code

### ISSUE THREAD

**Issue by morkovkin** [ValeryPonomarenko/ComponentsManager#1]
Hello ValeryPonomarenko! Thanks for your work! It's really nice work! i have question about android services and dagger depends.. can you add more example about usability in custom android view / services and so on...

**Comment by ValeryPonomarenko** [comment]
Hi, Evgeny!
Thank you for the question.

You can use the `findComponent<ComponentClass>()` in order to inject in the custom views or services.

Also, you can use the `bindComponentToCustomLifecycle<ComponentClass>(this)` to create a component with custom lifecycle. In this case you are responsible for the component's lifecycle, so you must remove it when you don't need it any more.

Read more about [Find component](https://github.com/ValeryPonomarenko/ComponentsManager/wiki/Find-component) and [Custom Lifecycle](https://github.com/ValeryPonomarenko/ComponentsManager/wiki/Custom-lifecycle)
