### ISSUE TITLE
Change configuration

### ISSUE THREAD

**Issue by eduard1abdulmanov123** [ValeryPonomarenko/ComponentsManager#6]
Good afternoon, when using your library, only the top fragment survives the configuration change, I think this is due to the use of FragmentManager.FragmentLifecycleCallbacks ().

**Comment by KostyaLyapochkin** [comment]
@ValeryPonomarenko Could you take a look? Because It's a big problem. 
You have this snippet of code 

```
if (isInSaveState) {
     isInSaveState = false <-- why have you added this point?
     return
}
```

For instance, I have some fragments in a stack like A-B. "B" took over the stack's top but when an app changes configuration (like rotation), XFragmentLifecycleHelper.class destroys components of all fragments which are lower in the stack, so "A" re-creating it's component until "A" occupies the top of stack and so on. 

I think that you should delete this point because XFragmentLifecycleHelper calls onFragmentStarted and onFragmentResumed methods which set isInSaveState = false up
